// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqRyVLRsPqbV8EVLErrh_YOaeGnO-A3A4',
    appId: '1:824515968706:web:bafbcfbf651e658a4b855b',
    messagingSenderId: '824515968706',
    projectId: 'busan-publicdata-startup-2025',
    authDomain: 'busan-publicdata-startup-2025.firebaseapp.com',
    storageBucket: 'busan-publicdata-startup-2025.firebasestorage.app',
    measurementId: 'G-5MPKMQ3YVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYWBsbwhibTh4I6VzW75G8zonSvYburLQ',
    appId: '1:824515968706:android:e8aa73e5e5a3841c4b855b',
    messagingSenderId: '824515968706',
    projectId: 'busan-publicdata-startup-2025',
    storageBucket: 'busan-publicdata-startup-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQD3zY_To8fUwKlCAC4q9mMRjV_7uwBQo',
    appId: '1:824515968706:ios:24340522fb59473c4b855b',
    messagingSenderId: '824515968706',
    projectId: 'busan-publicdata-startup-2025',
    storageBucket: 'busan-publicdata-startup-2025.firebasestorage.app',
    iosBundleId: 'com.example.busanPublicdataStartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQD3zY_To8fUwKlCAC4q9mMRjV_7uwBQo',
    appId: '1:824515968706:ios:24340522fb59473c4b855b',
    messagingSenderId: '824515968706',
    projectId: 'busan-publicdata-startup-2025',
    storageBucket: 'busan-publicdata-startup-2025.firebasestorage.app',
    iosBundleId: 'com.example.busanPublicdataStartup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqRyVLRsPqbV8EVLErrh_YOaeGnO-A3A4',
    appId: '1:824515968706:web:9a335564a9b542904b855b',
    messagingSenderId: '824515968706',
    projectId: 'busan-publicdata-startup-2025',
    authDomain: 'busan-publicdata-startup-2025.firebaseapp.com',
    storageBucket: 'busan-publicdata-startup-2025.firebasestorage.app',
    measurementId: 'G-3HF93R5QQQ',
  );
}
